// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEscuela.Models;

#nullable disable

namespace SistemaEscuela.Migrations
{
    [DbContext(typeof(SistemaEscuelaDbContext))]
    [Migration("20240420020649_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaEscuela.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Bhabilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Alumnos__3214EC077A05169B");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("SistemaEscuela.Models.Calificacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Bhabilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("Calificacion")
                        .HasColumnType("int");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int")
                        .HasColumnName("EstudianteID");

                    b.Property<int?>("MateriaId")
                        .HasColumnType("int")
                        .HasColumnName("MateriaID");

                    b.HasKey("Id")
                        .HasName("PK__Califica__3214EC079BC68BB1");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("SistemaEscuela.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool?>("Bhabilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<string>("NombreMateria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Materias__3214EC0730E78FDD");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("SistemaEscuela.Models.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int?>("IdMateria")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Matricul__3214EC070C7B4A29");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdMateria");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("SistemaEscuela.Models.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Bhabilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Profesor__3214EC075B7C163E");

                    b.ToTable("Profesor", (string)null);
                });

            modelBuilder.Entity("SistemaEscuela.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool?>("Bhabilitado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vista")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Rol__3214EC07C6515ADC");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("SistemaEscuela.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Bhabilitado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Pass")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("pass");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC07D3419575");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaEscuela.Models.Matricula", b =>
                {
                    b.HasOne("SistemaEscuela.Models.Alumno", "IdAlumnoNavigation")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdAlumno")
                        .HasConstraintName("FK__Matricula__IdAlu__59FA5E80");

                    b.HasOne("SistemaEscuela.Models.Materia", "IdMateriaNavigation")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdMateria")
                        .HasConstraintName("FK__Matricula__IdMat__59063A47");

                    b.Navigation("IdAlumnoNavigation");

                    b.Navigation("IdMateriaNavigation");
                });

            modelBuilder.Entity("SistemaEscuela.Models.Alumno", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("SistemaEscuela.Models.Materia", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
